create table "public"."app_feedback" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "link" text
);


alter table "public"."app_feedback" enable row level security;

CREATE UNIQUE INDEX app_feedback_pkey ON public.app_feedback USING btree (id);

alter table "public"."app_feedback" add constraint "app_feedback_pkey" PRIMARY KEY using index "app_feedback_pkey";

create policy "All get"
on "public"."app_feedback"
as permissive
for select
to public
using (true);


create policy "All get"
on "public"."suggested_challenge"
as permissive
for select
to public
using (true);



