create table "public"."app_ maintenance" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "maintenance_active" boolean not null default false
);


alter table "public"."app_ maintenance" enable row level security;

CREATE UNIQUE INDEX "app_ maintenance_pkey" ON public."app_ maintenance" USING btree (id);

alter table "public"."app_ maintenance" add constraint "app_ maintenance_pkey" PRIMARY KEY using index "app_ maintenance_pkey";

create policy "Everyone can get"
on "public"."app_ maintenance"
as permissive
for select
to public
using (true);



