import { supabase } from "@/lib/supabase";

/*
create table
  public.app_ maintenance (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    maintenance_active boolean not null default false,
    constraint app_ maintenance_pkey primary key (id)
  ) tablespace pg_default;
*/

export const getIsMaintenance = async (): Promise<boolean> => {
  try {
    const { data, error } = await supabase
      .from("app_ maintenance")
      .select("*")
      .order("created_at", { ascending: false })
      .limit(1);

    if (error) {
      throw error;
    }

    if (!data || data.length === 0) {
      throw new Error("No data found");
    }

    return data[0].maintenance_active;
  } catch (error) {
    console.error("Error getting app version:", error);
    return false;
  }
};
