import { supabase } from "@/lib/supabase";

/*
create table
  public.app_ maintenance (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    maintenance_active boolean not null default false,
    constraint app_ maintenance_pkey primary key (id)
  ) tablespace pg_default;
*/

export const getIsMaintenance = async (): Promise<{
  maintenance_active_ios: boolean;
  maintenance_active_android: boolean;
}> => {
  try {
    const { data, error } = await supabase
      .from("app_ maintenance")
      .select("*")
      .order("created_at", { ascending: false })
      .limit(1);

    if (error) {
      throw error;
    }

    if (!data || data.length === 0) {
      throw new Error("No data found");
    }

    return {
      maintenance_active_ios: data[0].maintenance_active,
      maintenance_active_android: data[0].maintenance_active_android,
    };
  } catch (error) {
    // console.error("Error getting app version:", error);
    return {
      maintenance_active_ios: false,
      maintenance_active_android: false,
    };
  }
};
